//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.Library.Resources
{
	using System;
	using System.Reflection;

    
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute ()]
	internal class English
	{
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal English ()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals (resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager ("Jornalero.Library.English", typeof(English).GetTypeInfo ().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Share your favorite spots with the world.
		/// </summary>
		internal static string _1 {
			get {
				return ResourceManager.GetString ("1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Welcome back!.
		/// </summary>
		internal static string _10 {
			get {
				return ResourceManager.GetString ("10", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) upvoted your post at (location).
		/// </summary>
		internal static string _100 {
			get {
				return ResourceManager.GetString ("100", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) commented on your post at (location).
		/// </summary>
		internal static string _101 {
			get {
				return ResourceManager.GetString ("101", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) commented on a post you commented on at (location).
		/// </summary>
		internal static string _102 {
			get {
				return ResourceManager.GetString ("102", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to edit profile.
		/// </summary>
		internal static string _103 {
			get {
				return ResourceManager.GetString ("103", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Recent activity.
		/// </summary>
		internal static string _104 {
			get {
				return ResourceManager.GetString ("104", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Change image.
		/// </summary>
		internal static string _105 {
			get {
				return ResourceManager.GetString ("105", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edit handle.
		/// </summary>
		internal static string _106 {
			get {
				return ResourceManager.GetString ("106", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No activity yet :{.
		/// </summary>
		internal static string _107 {
			get {
				return ResourceManager.GetString ("107", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to a post at.
		/// </summary>
		internal static string _108 {
			get {
				return ResourceManager.GetString ("108", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to posted.
		/// </summary>
		internal static string _109 {
			get {
				return ResourceManager.GetString ("109", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sign in.
		/// </summary>
		internal static string _11 {
			get {
				return ResourceManager.GetString ("11", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to commented.
		/// </summary>
		internal static string _110 {
			get {
				return ResourceManager.GetString ("110", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to upvoted.
		/// </summary>
		internal static string _111 {
			get {
				return ResourceManager.GetString ("111", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Comment email notifications.
		/// </summary>
		internal static string _112 {
			get {
				return ResourceManager.GetString ("112", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Comment push notifications.
		/// </summary>
		internal static string _113 {
			get {
				return ResourceManager.GetString ("113", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Upvote push notifications.
		/// </summary>
		internal static string _114 {
			get {
				return ResourceManager.GetString ("114", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nearby push notifications.
		/// </summary>
		internal static string _115 {
			get {
				return ResourceManager.GetString ("115", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Other.
		/// </summary>
		internal static string _116 {
			get {
				return ResourceManager.GetString ("116", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Support.
		/// </summary>
		internal static string _117 {
			get {
				return ResourceManager.GetString ("117", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to App store review.
		/// </summary>
		internal static string _118 {
			get {
				return ResourceManager.GetString ("118", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to blog.
		/// </summary>
		internal static string _119 {
			get {
				return ResourceManager.GetString ("119", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Forgot your password?.
		/// </summary>
		internal static string _12 {
			get {
				return ResourceManager.GetString ("12", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Terms of Use.
		/// </summary>
		internal static string _120 {
			get {
				return ResourceManager.GetString ("120", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Privacy Policy.
		/// </summary>
		internal static string _121 {
			get {
				return ResourceManager.GetString ("121", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sign out.
		/// </summary>
		internal static string _122 {
			get {
				return ResourceManager.GetString ("122", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Current build.
		/// </summary>
		internal static string _123 {
			get {
				return ResourceManager.GetString ("123", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Teleport.
		/// </summary>
		internal static string _124 {
			get {
				return ResourceManager.GetString ("124", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Current location.
		/// </summary>
		internal static string _125 {
			get {
				return ResourceManager.GetString ("125", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trending Places.
		/// </summary>
		internal static string _126 {
			get {
				return ResourceManager.GetString ("126", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to These are the hottest locations in Spark right now! Watch for more coming soon..
		/// </summary>
		internal static string _127 {
			get {
				return ResourceManager.GetString ("127", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Details.
		/// </summary>
		internal static string _128 {
			get {
				return ResourceManager.GetString ("128", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Share.
		/// </summary>
		internal static string _129 {
			get {
				return ResourceManager.GetString ("129", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reset password.
		/// </summary>
		internal static string _13 {
			get {
				return ResourceManager.GetString ("13", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Your comment.
		/// </summary>
		internal static string _130 {
			get {
				return ResourceManager.GetString ("130", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Get directions.
		/// </summary>
		internal static string _131 {
			get {
				return ResourceManager.GetString ("131", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Flag.
		/// </summary>
		internal static string _132 {
			get {
				return ResourceManager.GetString ("132", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to comment.
		/// </summary>
		internal static string _133 {
			get {
				return ResourceManager.GetString ("133", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to upvote.
		/// </summary>
		internal static string _134 {
			get {
				return ResourceManager.GetString ("134", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		internal static string _135 {
			get {
				return ResourceManager.GetString ("135", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add.
		/// </summary>
		internal static string _136 {
			get {
				return ResourceManager.GetString ("136", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Oops!.
		/// </summary>
		internal static string _137 {
			get {
				return ResourceManager.GetString ("137", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to There was a problem acessing the latest data. Do you want to try again?.
		/// </summary>
		internal static string _138 {
			get {
				return ResourceManager.GetString ("138", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No thanks.
		/// </summary>
		internal static string _139 {
			get {
				return ResourceManager.GetString ("139", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Signing you up for Spark.
		/// </summary>
		internal static string _14 {
			get {
				return ResourceManager.GetString ("14", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Try again.
		/// </summary>
		internal static string _140 {
			get {
				return ResourceManager.GetString ("140", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Missing info.
		/// </summary>
		internal static string _141 {
			get {
				return ResourceManager.GetString ("141", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Both email and password required.
		/// </summary>
		internal static string _142 {
			get {
				return ResourceManager.GetString ("142", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Bad email.
		/// </summary>
		internal static string _143 {
			get {
				return ResourceManager.GetString ("143", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to That doesn&apos;t look like a real email address to us.
		/// </summary>
		internal static string _144 {
			get {
				return ResourceManager.GetString ("144", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to That email is already in use. Maybe you want to sign in instead?.
		/// </summary>
		internal static string _145 {
			get {
				return ResourceManager.GetString ("145", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error loading nearby.
		/// </summary>
		internal static string _146 {
			get {
				return ResourceManager.GetString ("146", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Couldn&apos;t find you.
		/// </summary>
		internal static string _147 {
			get {
				return ResourceManager.GetString ("147", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Double check your email and password combination..
		/// </summary>
		internal static string _148 {
			get {
				return ResourceManager.GetString ("148", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sometimes size does matter!.
		/// </summary>
		internal static string _149 {
			get {
				return ResourceManager.GetString ("149", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Customize your profile.
		/// </summary>
		internal static string _15 {
			get {
				return ResourceManager.GetString ("15", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to We want your posts to look their very best so please only select images that are....
		/// </summary>
		internal static string _150 {
			get {
				return ResourceManager.GetString ("150", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This post is only an example.
		/// </summary>
		internal static string _151 {
			get {
				return ResourceManager.GetString ("151", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Had it been a real post you could upvote to help others find it..
		/// </summary>
		internal static string _152 {
			get {
				return ResourceManager.GetString ("152", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Had it been a real post you&apos;d be seeing a lot more detail right now..
		/// </summary>
		internal static string _153 {
			get {
				return ResourceManager.GetString ("153", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Right here.
		/// </summary>
		internal static string _154 {
			get {
				return ResourceManager.GetString ("154", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Your post is awesome.
		/// </summary>
		internal static string _155 {
			get {
				return ResourceManager.GetString ("155", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to We auto upvoted for you - because let&apos;s be honest, your post is awesome..
		/// </summary>
		internal static string _156 {
			get {
				return ResourceManager.GetString ("156", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No unvoting your own post.
		/// </summary>
		internal static string _157 {
			get {
				return ResourceManager.GetString ("157", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sign in failed.
		/// </summary>
		internal static string _158 {
			get {
				return ResourceManager.GetString ("158", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sign in failed unexpectedly. Please try again..
		/// </summary>
		internal static string _159 {
			get {
				return ResourceManager.GetString ("159", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Checking availability....
		/// </summary>
		internal static string _16 {
			get {
				return ResourceManager.GetString ("16", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Join Failed.
		/// </summary>
		internal static string _160 {
			get {
				return ResourceManager.GetString ("160", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Join failed unexpectedly. Please try again..
		/// </summary>
		internal static string _161 {
			get {
				return ResourceManager.GetString ("161", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notifications.
		/// </summary>
		internal static string _162 {
			get {
				return ResourceManager.GetString ("162", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First name.
		/// </summary>
		internal static string _163 {
			get {
				return ResourceManager.GetString ("163", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Last name.
		/// </summary>
		internal static string _164 {
			get {
				return ResourceManager.GetString ("164", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email.
		/// </summary>
		internal static string _165 {
			get {
				return ResourceManager.GetString ("165", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Saving the new you....
		/// </summary>
		internal static string _17 {
			get {
				return ResourceManager.GetString ("17", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Take photo.
		/// </summary>
		internal static string _18 {
			get {
				return ResourceManager.GetString ("18", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose existing photo.
		/// </summary>
		internal static string _19 {
			get {
				return ResourceManager.GetString ("19", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to What makes your neighborhood awesome?.
		/// </summary>
		internal static string _2 {
			get {
				return ResourceManager.GetString ("2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		internal static string _20 {
			get {
				return ResourceManager.GetString ("20", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		internal static string _21 {
			get {
				return ResourceManager.GetString ("21", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Logging in.
		/// </summary>
		internal static string _22 {
			get {
				return ResourceManager.GetString ("22", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Joining .
		/// </summary>
		internal static string _23 {
			get {
				return ResourceManager.GetString ("23", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Location, Location, Location.
		/// </summary>
		internal static string _24 {
			get {
				return ResourceManager.GetString ("24", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark shows you what people in your area are up to. Allow Spark to access your location and join in the adventure!.
		/// </summary>
		internal static string _25 {
			get {
				return ResourceManager.GetString ("25", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Onward.
		/// </summary>
		internal static string _26 {
			get {
				return ResourceManager.GetString ("26", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Your phone settings have location disabled. .
		/// </summary>
		internal static string _27 {
			get {
				return ResourceManager.GetString ("27", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Go to settings.
		/// </summary>
		internal static string _28 {
			get {
				return ResourceManager.GetString ("28", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Explore with Spark....
		/// </summary>
		internal static string _29 {
			get {
				return ResourceManager.GetString ("29", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Find the places that locals love..
		/// </summary>
		internal static string _3 {
			get {
				return ResourceManager.GetString ("3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enable your phone&apos;s location to explore and share what&apos;s happening near you..
		/// </summary>
		internal static string _30 {
			get {
				return ResourceManager.GetString ("30", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to View San Francisco.
		/// </summary>
		internal static string _31 {
			get {
				return ResourceManager.GetString ("31", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Logging you in to Spark....
		/// </summary>
		internal static string _32 {
			get {
				return ResourceManager.GetString ("32", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark uses location to show you the exciting experiences users are having nearby. It&apos;s private and secure..
		/// </summary>
		internal static string _33 {
			get {
				return ResourceManager.GetString ("33", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allow Spark to use your location to explore and share what&apos;s happening near you..
		/// </summary>
		internal static string _34 {
			get {
				return ResourceManager.GetString ("34", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allow Spark to use your location.
		/// </summary>
		internal static string _35 {
			get {
				return ResourceManager.GetString ("35", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not ready yet? Test drive Spark and see the San Francisco only locals know..
		/// </summary>
		internal static string _36 {
			get {
				return ResourceManager.GetString ("36", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Settings.
		/// </summary>
		internal static string _37 {
			get {
				return ResourceManager.GetString ("37", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not yet.
		/// </summary>
		internal static string _38 {
			get {
				return ResourceManager.GetString ("38", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Get the party started!.
		/// </summary>
		internal static string _39 {
			get {
				return ResourceManager.GetString ("39", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Continue with Email.
		/// </summary>
		internal static string _4 {
			get {
				return ResourceManager.GetString ("4", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Looks like you are one of the first users in your area! Kick off the fun by sharing what&apos;s happening in your area..
		/// </summary>
		internal static string _40 {
			get {
				return ResourceManager.GetString ("40", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark shows you trending experiences in your area. Get Inspired!.
		/// </summary>
		internal static string _41 {
			get {
				return ResourceManager.GetString ("41", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Posts show what&apos;s cool in your area. What&apos;s happening near you?.
		/// </summary>
		internal static string _42 {
			get {
				return ResourceManager.GetString ("42", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Upvote posts to give kudos and spread the word.
		/// </summary>
		internal static string _43 {
			get {
				return ResourceManager.GetString ("43", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Discover near you in....
		/// </summary>
		internal static string _44 {
			get {
				return ResourceManager.GetString ("44", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to When you want to post your favorite events, spots or views with others tap....
		/// </summary>
		internal static string _45 {
			get {
				return ResourceManager.GetString ("45", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spinning the hamster wheels.
		/// </summary>
		internal static string _46 {
			get {
				return ResourceManager.GetString ("46", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warming up the flux capacitor.
		/// </summary>
		internal static string _47 {
			get {
				return ResourceManager.GetString ("47", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finding the nearest awesome.
		/// </summary>
		internal static string _48 {
			get {
				return ResourceManager.GetString ("48", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Priming the latest fun around you.
		/// </summary>
		internal static string _49 {
			get {
				return ResourceManager.GetString ("49", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create your account.
		/// </summary>
		internal static string _5 {
			get {
				return ResourceManager.GetString ("5", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reticulating splines.
		/// </summary>
		internal static string _50 {
			get {
				return ResourceManager.GetString ("50", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Energizing....
		/// </summary>
		internal static string _51 {
			get {
				return ResourceManager.GetString ("51", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to I&apos;m giving her all she&apos;s got.
		/// </summary>
		internal static string _52 {
			get {
				return ResourceManager.GetString ("52", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Contacting Scotty.
		/// </summary>
		internal static string _53 {
			get {
				return ResourceManager.GetString ("53", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warp speed engage.
		/// </summary>
		internal static string _54 {
			get {
				return ResourceManager.GetString ("54", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Hacking quantum physics.
		/// </summary>
		internal static string _55 {
			get {
				return ResourceManager.GetString ("55", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nearby places incoming.
		/// </summary>
		internal static string _56 {
			get {
				return ResourceManager.GetString ("56", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Grabbing nearby places.
		/// </summary>
		internal static string _57 {
			get {
				return ResourceManager.GetString ("57", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Flipping through the yellow pages.
		/// </summary>
		internal static string _58 {
			get {
				return ResourceManager.GetString ("58", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Posting to your local Spark.
		/// </summary>
		internal static string _59 {
			get {
				return ResourceManager.GetString ("59", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email address.
		/// </summary>
		internal static string _6 {
			get {
				return ResourceManager.GetString ("6", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sharing is caring.
		/// </summary>
		internal static string _60 {
			get {
				return ResourceManager.GetString ("60", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sharing fun.
		/// </summary>
		internal static string _61 {
			get {
				return ResourceManager.GetString ("61", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nearby.
		/// </summary>
		internal static string _62 {
			get {
				return ResourceManager.GetString ("62", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notifications.
		/// </summary>
		internal static string _63 {
			get {
				return ResourceManager.GetString ("63", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Profile.
		/// </summary>
		internal static string _64 {
			get {
				return ResourceManager.GetString ("64", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to List.
		/// </summary>
		internal static string _65 {
			get {
				return ResourceManager.GetString ("65", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This is a public Instagram post we think you&apos;ll like.
		/// </summary>
		internal static string _66 {
			get {
				return ResourceManager.GetString ("66", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Getting upvotes earns you cooler titles. Show off your street cred!.
		/// </summary>
		internal static string _67 {
			get {
				return ResourceManager.GetString ("67", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Here are the top trending posts near you!.
		/// </summary>
		internal static string _68 {
			get {
				return ResourceManager.GetString ("68", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ask a question, leave a note, or just give props!.
		/// </summary>
		internal static string _69 {
			get {
				return ResourceManager.GetString ("69", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password.
		/// </summary>
		internal static string _7 {
			get {
				return ResourceManager.GetString ("7", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Astronaut.
		/// </summary>
		internal static string _70 {
			get {
				return ResourceManager.GetString ("70", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Newcomer.
		/// </summary>
		internal static string _71 {
			get {
				return ResourceManager.GetString ("71", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Apprentice.
		/// </summary>
		internal static string _72 {
			get {
				return ResourceManager.GetString ("72", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Scout .
		/// </summary>
		internal static string _73 {
			get {
				return ResourceManager.GetString ("73", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Explorer.
		/// </summary>
		internal static string _74 {
			get {
				return ResourceManager.GetString ("74", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trailblazer.
		/// </summary>
		internal static string _75 {
			get {
				return ResourceManager.GetString ("75", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to now.
		/// </summary>
		internal static string _76 {
			get {
				return ResourceManager.GetString ("76", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to mins.
		/// </summary>
		internal static string _77 {
			get {
				return ResourceManager.GetString ("77", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to minutes.
		/// </summary>
		internal static string _78 {
			get {
				return ResourceManager.GetString ("78", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to hours.
		/// </summary>
		internal static string _79 {
			get {
				return ResourceManager.GetString ("79", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Submit.
		/// </summary>
		internal static string _8 {
			get {
				return ResourceManager.GetString ("8", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to days.
		/// </summary>
		internal static string _80 {
			get {
				return ResourceManager.GetString ("80", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to weeks.
		/// </summary>
		internal static string _81 {
			get {
				return ResourceManager.GetString ("81", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to months.
		/// </summary>
		internal static string _82 {
			get {
				return ResourceManager.GetString ("82", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Share what&apos;s happening around you....
		/// </summary>
		internal static string _83 {
			get {
				return ResourceManager.GetString ("83", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Tag a place.
		/// </summary>
		internal static string _84 {
			get {
				return ResourceManager.GetString ("84", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Current spot.
		/// </summary>
		internal static string _85 {
			get {
				return ResourceManager.GetString ("85", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create new post.
		/// </summary>
		internal static string _86 {
			get {
				return ResourceManager.GetString ("86", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Post.
		/// </summary>
		internal static string _87 {
			get {
				return ResourceManager.GetString ("87", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Posting.
		/// </summary>
		internal static string _88 {
			get {
				return ResourceManager.GetString ("88", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Share this awesome post with your friends on Facebook and Twitter.
		/// </summary>
		internal static string _89 {
			get {
				return ResourceManager.GetString ("89", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Already have an account?.
		/// </summary>
		internal static string _9 {
			get {
				return ResourceManager.GetString ("9", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark works best when you know the latest!.
		/// </summary>
		internal static string _90 {
			get {
				return ResourceManager.GetString ("90", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Turn on push notifications to know right away when fellow Sparks interact with your posts..
		/// </summary>
		internal static string _91 {
			get {
				return ResourceManager.GetString ("91", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to not now.
		/// </summary>
		internal static string _92 {
			get {
				return ResourceManager.GetString ("92", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notify me!.
		/// </summary>
		internal static string _93 {
			get {
				return ResourceManager.GetString ("93", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nothing to see here yet!.
		/// </summary>
		internal static string _94 {
			get {
				return ResourceManager.GetString ("94", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Connect with those around you and before you know it you&apos;ll have some notifications here ;).
		/// </summary>
		internal static string _95 {
			get {
				return ResourceManager.GetString ("95", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notification.
		/// </summary>
		internal static string _96 {
			get {
				return ResourceManager.GetString ("96", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Close.
		/// </summary>
		internal static string _97 {
			get {
				return ResourceManager.GetString ("97", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Take me to it!.
		/// </summary>
		internal static string _98 {
			get {
				return ResourceManager.GetString ("98", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) commented on a post you upvoted at (location).
		/// </summary>
		internal static string _99 {
			get {
				return ResourceManager.GetString ("99", resourceCulture);
			}
		}
	}
}
