//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.Library.Resources
{
	using System;
	using System.Reflection;

    
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute ()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute ()]
	internal class Spanish
	{
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Spanish ()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals (resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager ("Jornalero.Library.Spanish", typeof(Spanish).GetTypeInfo ().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute (global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поделитесь своими любимыми местами с миром.
		/// </summary>
		internal static string _1 {
			get {
				return ResourceManager.GetString ("1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Добро пожаловать!.
		/// </summary>
		internal static string _10 {
			get {
				return ResourceManager.GetString ("10", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) оценил(а) ваш пост про (location).
		/// </summary>
		internal static string _100 {
			get {
				return ResourceManager.GetString ("100", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) прокомментировал(а) ваш пост про (location).
		/// </summary>
		internal static string _101 {
			get {
				return ResourceManager.GetString ("101", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) ответил(а) на ваш пост про (location).
		/// </summary>
		internal static string _102 {
			get {
				return ResourceManager.GetString ("102", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Редактировать профиль.
		/// </summary>
		internal static string _103 {
			get {
				return ResourceManager.GetString ("103", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Недавняя активность.
		/// </summary>
		internal static string _104 {
			get {
				return ResourceManager.GetString ("104", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Изменить фотографию.
		/// </summary>
		internal static string _105 {
			get {
				return ResourceManager.GetString ("105", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Изменить имя пользователя.
		/// </summary>
		internal static string _106 {
			get {
				return ResourceManager.GetString ("106", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пока нет активности :{.
		/// </summary>
		internal static string _107 {
			get {
				return ResourceManager.GetString ("107", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to пост.
		/// </summary>
		internal static string _108 {
			get {
				return ResourceManager.GetString ("108", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to опубликовано.
		/// </summary>
		internal static string _109 {
			get {
				return ResourceManager.GetString ("109", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Войти.
		/// </summary>
		internal static string _11 {
			get {
				return ResourceManager.GetString ("11", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to прокомментировано.
		/// </summary>
		internal static string _110 {
			get {
				return ResourceManager.GetString ("110", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to оценено.
		/// </summary>
		internal static string _111 {
			get {
				return ResourceManager.GetString ("111", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to комментариях по эл. почте.
		/// </summary>
		internal static string _112 {
			get {
				return ResourceManager.GetString ("112", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Push о комментариях.
		/// </summary>
		internal static string _113 {
			get {
				return ResourceManager.GetString ("113", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Push об оценках.
		/// </summary>
		internal static string _114 {
			get {
				return ResourceManager.GetString ("114", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Push о местах поблизости.
		/// </summary>
		internal static string _115 {
			get {
				return ResourceManager.GetString ("115", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Другое.
		/// </summary>
		internal static string _116 {
			get {
				return ResourceManager.GetString ("116", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поддержка.
		/// </summary>
		internal static string _117 {
			get {
				return ResourceManager.GetString ("117", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Анализ App Store.
		/// </summary>
		internal static string _118 {
			get {
				return ResourceManager.GetString ("118", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to блог.
		/// </summary>
		internal static string _119 {
			get {
				return ResourceManager.GetString ("119", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Забыли пароль?.
		/// </summary>
		internal static string _12 {
			get {
				return ResourceManager.GetString ("12", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Условия использования.
		/// </summary>
		internal static string _120 {
			get {
				return ResourceManager.GetString ("120", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Политика Конфиденциальности.
		/// </summary>
		internal static string _121 {
			get {
				return ResourceManager.GetString ("121", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Выйти.
		/// </summary>
		internal static string _122 {
			get {
				return ResourceManager.GetString ("122", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Текущая версия.
		/// </summary>
		internal static string _123 {
			get {
				return ResourceManager.GetString ("123", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Телепорт.
		/// </summary>
		internal static string _124 {
			get {
				return ResourceManager.GetString ("124", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Текущее местоположение.
		/// </summary>
		internal static string _125 {
			get {
				return ResourceManager.GetString ("125", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Популярные места.
		/// </summary>
		internal static string _126 {
			get {
				return ResourceManager.GetString ("126", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Самые горячие места в Spark прямо сейчас! Продолжайте следить за новинками..
		/// </summary>
		internal static string _127 {
			get {
				return ResourceManager.GetString ("127", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Детали.
		/// </summary>
		internal static string _128 {
			get {
				return ResourceManager.GetString ("128", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поделиться.
		/// </summary>
		internal static string _129 {
			get {
				return ResourceManager.GetString ("129", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Восстановить пароль.
		/// </summary>
		internal static string _13 {
			get {
				return ResourceManager.GetString ("13", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ваш комментарий.
		/// </summary>
		internal static string _130 {
			get {
				return ResourceManager.GetString ("130", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Получить координаты.
		/// </summary>
		internal static string _131 {
			get {
				return ResourceManager.GetString ("131", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отметить место.
		/// </summary>
		internal static string _132 {
			get {
				return ResourceManager.GetString ("132", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to прокомментировано.
		/// </summary>
		internal static string _133 {
			get {
				return ResourceManager.GetString ("133", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to оценено.
		/// </summary>
		internal static string _134 {
			get {
				return ResourceManager.GetString ("134", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отменить.
		/// </summary>
		internal static string _135 {
			get {
				return ResourceManager.GetString ("135", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Добавить.
		/// </summary>
		internal static string _136 {
			get {
				return ResourceManager.GetString ("136", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ой!.
		/// </summary>
		internal static string _137 {
			get {
				return ResourceManager.GetString ("137", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проблема в загрузке последних данных. Хотите попробовать ещё раз?.
		/// </summary>
		internal static string _138 {
			get {
				return ResourceManager.GetString ("138", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Нет, спасибо.
		/// </summary>
		internal static string _139 {
			get {
				return ResourceManager.GetString ("139", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Регистрация в Spark.
		/// </summary>
		internal static string _14 {
			get {
				return ResourceManager.GetString ("14", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ещё раз.
		/// </summary>
		internal static string _140 {
			get {
				return ResourceManager.GetString ("140", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Не хватает данных.
		/// </summary>
		internal static string _141 {
			get {
				return ResourceManager.GetString ("141", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Необходим адрес эл.почты и пароль.
		/// </summary>
		internal static string _142 {
			get {
				return ResourceManager.GetString ("142", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Неверная эл.почта.
		/// </summary>
		internal static string _143 {
			get {
				return ResourceManager.GetString ("143", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Похоже это неверный адрес эл.почты.
		/// </summary>
		internal static string _144 {
			get {
				return ResourceManager.GetString ("144", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Эта эл.почта уже используется. Может вы хотите войти?.
		/// </summary>
		internal static string _145 {
			get {
				return ResourceManager.GetString ("145", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ошибка загрузки мест поблизости.
		/// </summary>
		internal static string _146 {
			get {
				return ResourceManager.GetString ("146", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Не можем вас найти.
		/// </summary>
		internal static string _147 {
			get {
				return ResourceManager.GetString ("147", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проверьте ещё раз сочетание эл.почты и пароля..
		/// </summary>
		internal static string _148 {
			get {
				return ResourceManager.GetString ("148", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Иногда размер имеет значение!.
		/// </summary>
		internal static string _149 {
			get {
				return ResourceManager.GetString ("149", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Настройте свой профиль.
		/// </summary>
		internal static string _15 {
			get {
				return ResourceManager.GetString ("15", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Мы хотим, чтобы ваши посты выглядели супер. Пожалуйста, выберите фото, которые....
		/// </summary>
		internal static string _150 {
			get {
				return ResourceManager.GetString ("150", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пример поста.
		/// </summary>
		internal static string _151 {
			get {
				return ResourceManager.GetString ("151", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Могли бы вы проголосовать за этот пост, чтобы другие нашли его?.
		/// </summary>
		internal static string _152 {
			get {
				return ResourceManager.GetString ("152", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Мог бы этот пост помочь вам увидеть дополнительные детали?.
		/// </summary>
		internal static string _153 {
			get {
				return ResourceManager.GetString ("153", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Прямо здесь.
		/// </summary>
		internal static string _154 {
			get {
				return ResourceManager.GetString ("154", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Потрясающий пост!.
		/// </summary>
		internal static string _155 {
			get {
				return ResourceManager.GetString ("155", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Мы автоматически проголосовали за вас. Если честно, ваш пост просто потрясающий!.
		/// </summary>
		internal static string _156 {
			get {
				return ResourceManager.GetString ("156", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Нельзя отменить голосование своему посту.
		/// </summary>
		internal static string _157 {
			get {
				return ResourceManager.GetString ("157", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ошибка входа.
		/// </summary>
		internal static string _158 {
			get {
				return ResourceManager.GetString ("158", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ошибка входа. Попробуйте ещё раз..
		/// </summary>
		internal static string _159 {
			get {
				return ResourceManager.GetString ("159", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проверяем наличие....
		/// </summary>
		internal static string _16 {
			get {
				return ResourceManager.GetString ("16", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Попытка не удалась.
		/// </summary>
		internal static string _160 {
			get {
				return ResourceManager.GetString ("160", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Попытка не удалась. Пожалуйста, попробуйте ещё раз..
		/// </summary>
		internal static string _161 {
			get {
				return ResourceManager.GetString ("161", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Уведомления.
		/// </summary>
		internal static string _162 {
			get {
				return ResourceManager.GetString ("162", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to имя.
		/// </summary>
		internal static string _163 {
			get {
				return ResourceManager.GetString ("163", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Фамилия.
		/// </summary>
		internal static string _164 {
			get {
				return ResourceManager.GetString ("164", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to эл.почта.
		/// </summary>
		internal static string _165 {
			get {
				return ResourceManager.GetString ("165", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Сохраняем вас....
		/// </summary>
		internal static string _17 {
			get {
				return ResourceManager.GetString ("17", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Сделать фото.
		/// </summary>
		internal static string _18 {
			get {
				return ResourceManager.GetString ("18", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Выберать фотографию.
		/// </summary>
		internal static string _19 {
			get {
				return ResourceManager.GetString ("19", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Что делает ваш район удивительным?.
		/// </summary>
		internal static string _2 {
			get {
				return ResourceManager.GetString ("2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отменить.
		/// </summary>
		internal static string _20 {
			get {
				return ResourceManager.GetString ("20", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Сохранить.
		/// </summary>
		internal static string _21 {
			get {
				return ResourceManager.GetString ("21", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Вход в систему.
		/// </summary>
		internal static string _22 {
			get {
				return ResourceManager.GetString ("22", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Добавление.
		/// </summary>
		internal static string _23 {
			get {
				return ResourceManager.GetString ("23", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Местонахождение, Местонахождение, Местонахождение.
		/// </summary>
		internal static string _24 {
			get {
				return ResourceManager.GetString ("24", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark показывает, чем заняты люди в вашем районе. Предоставьте Spark доступ к вашему местонахождению, и пускайтесь в приключения!.
		/// </summary>
		internal static string _25 {
			get {
				return ResourceManager.GetString ("25", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Далее.
		/// </summary>
		internal static string _26 {
			get {
				return ResourceManager.GetString ("26", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to В вашем телефоне отключены настройки локации..
		/// </summary>
		internal static string _27 {
			get {
				return ResourceManager.GetString ("27", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to В настройки.
		/// </summary>
		internal static string _28 {
			get {
				return ResourceManager.GetString ("28", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Исследовать с Spark....
		/// </summary>
		internal static string _29 {
			get {
				return ResourceManager.GetString ("29", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Найдите места, которые любят местные жители.
		/// </summary>
		internal static string _3 {
			get {
				return ResourceManager.GetString ("3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Включить местоположение вашего телефона, чтобы исследовать и поделиться тем, что происходит рядом с вами..
		/// </summary>
		internal static string _30 {
			get {
				return ResourceManager.GetString ("30", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Показать Сан-Франциско.
		/// </summary>
		internal static string _31 {
			get {
				return ResourceManager.GetString ("31", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Подключаемся к Spark....
		/// </summary>
		internal static string _32 {
			get {
				return ResourceManager.GetString ("32", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark использует местонахождение, чтобы поделиться с вами захватывающим опытом пользователей, которые рядом. Это конфиденциально и безопасно..
		/// </summary>
		internal static string _33 {
			get {
				return ResourceManager.GetString ("33", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Разрешите Spark использовать ваше местонахождение, чтобы обнаружить и поделиться тем, что происходит рядом с вами..
		/// </summary>
		internal static string _34 {
			get {
				return ResourceManager.GetString ("34", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Разрешить Spark использовать ваше местоположение.
		/// </summary>
		internal static string _35 {
			get {
				return ResourceManager.GetString ("35", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пока не готовы? Попробуйте Spark для Сан-Франциско, который знают только местные жители. .
		/// </summary>
		internal static string _36 {
			get {
				return ResourceManager.GetString ("36", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Настройки.
		/// </summary>
		internal static string _37 {
			get {
				return ResourceManager.GetString ("37", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ещё нет.
		/// </summary>
		internal static string _38 {
			get {
				return ResourceManager.GetString ("38", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Начинаем веселиться!.
		/// </summary>
		internal static string _39 {
			get {
				return ResourceManager.GetString ("39", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Продолжить с эл.почтой.
		/// </summary>
		internal static string _4 {
			get {
				return ResourceManager.GetString ("4", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Похоже, вы один из первых пользователей в вашем районе! Начните первым делиться тем, что происходит в вашем районе..
		/// </summary>
		internal static string _40 {
			get {
				return ResourceManager.GetString ("40", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark показывает главные тенденции в вашем районе. Вдохновитесь!.
		/// </summary>
		internal static string _41 {
			get {
				return ResourceManager.GetString ("41", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Посты показывают, что есть крутого в вашем районе. Что происходит рядом с вами?.
		/// </summary>
		internal static string _42 {
			get {
				return ResourceManager.GetString ("42", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Оценивайте посты, чтобы повысить рейтинг и рассказать другим.
		/// </summary>
		internal static string _43 {
			get {
				return ResourceManager.GetString ("43", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Найти рядом с вами в....
		/// </summary>
		internal static string _44 {
			get {
				return ResourceManager.GetString ("44", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Если хотите добавить ваши любимые события, места, и разделить мнение с другими, нажмите....
		/// </summary>
		internal static string _45 {
			get {
				return ResourceManager.GetString ("45", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Бегаем как белка в колесе.
		/// </summary>
		internal static string _46 {
			get {
				return ResourceManager.GetString ("46", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Заводим ускоритель.
		/// </summary>
		internal static string _47 {
			get {
				return ResourceManager.GetString ("47", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ищем ближайщее классное место.
		/// </summary>
		internal static string _48 {
			get {
				return ResourceManager.GetString ("48", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Зажигаем веселье рядом с вами.
		/// </summary>
		internal static string _49 {
			get {
				return ResourceManager.GetString ("49", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Создать аккаунт.
		/// </summary>
		internal static string _5 {
			get {
				return ResourceManager.GetString ("5", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Загружаем информацию.
		/// </summary>
		internal static string _50 {
			get {
				return ResourceManager.GetString ("50", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Заряжаемся.....
		/// </summary>
		internal static string _51 {
			get {
				return ResourceManager.GetString ("51", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Выжимаемся по-максимуму.
		/// </summary>
		internal static string _52 {
			get {
				return ResourceManager.GetString ("52", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Звоним главному инженеру.
		/// </summary>
		internal static string _53 {
			get {
				return ResourceManager.GetString ("53", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Включаем максимальную скорость.
		/// </summary>
		internal static string _54 {
			get {
				return ResourceManager.GetString ("54", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Постигаем квантовую физику.
		/// </summary>
		internal static string _55 {
			get {
				return ResourceManager.GetString ("55", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Исследуем места поблизости.
		/// </summary>
		internal static string _56 {
			get {
				return ResourceManager.GetString ("56", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Исследуем места поблизости.
		/// </summary>
		internal static string _57 {
			get {
				return ResourceManager.GetString ("57", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Перелистываем справочник.
		/// </summary>
		internal static string _58 {
			get {
				return ResourceManager.GetString ("58", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Размещаем сообщения о местах поблизости в Spark.
		/// </summary>
		internal static string _59 {
			get {
				return ResourceManager.GetString ("59", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Электр. адрес.
		/// </summary>
		internal static string _6 {
			get {
				return ResourceManager.GetString ("6", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Делиться - хорошо! .
		/// </summary>
		internal static string _60 {
			get {
				return ResourceManager.GetString ("60", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Делимся весельем.
		/// </summary>
		internal static string _61 {
			get {
				return ResourceManager.GetString ("61", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поблизости.
		/// </summary>
		internal static string _62 {
			get {
				return ResourceManager.GetString ("62", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Уведомления.
		/// </summary>
		internal static string _63 {
			get {
				return ResourceManager.GetString ("63", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Профиль.
		/// </summary>
		internal static string _64 {
			get {
				return ResourceManager.GetString ("64", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Список.
		/// </summary>
		internal static string _65 {
			get {
				return ResourceManager.GetString ("65", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Это открытый пост Instagram, который вам должен понравится.
		/// </summary>
		internal static string _66 {
			get {
				return ResourceManager.GetString ("66", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Оценка постов даст вам крутое звание. Похвастуйтесь своим авторитетом!.
		/// </summary>
		internal static string _67 {
			get {
				return ResourceManager.GetString ("67", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Вот топ сообщений о местах рядом с вами!.
		/// </summary>
		internal static string _68 {
			get {
				return ResourceManager.GetString ("68", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Задайте вопрос, напишите заметку, или просто поблагодарите!.
		/// </summary>
		internal static string _69 {
			get {
				return ResourceManager.GetString ("69", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пароль.
		/// </summary>
		internal static string _7 {
			get {
				return ResourceManager.GetString ("7", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Космонавт.
		/// </summary>
		internal static string _70 {
			get {
				return ResourceManager.GetString ("70", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пришелец.
		/// </summary>
		internal static string _71 {
			get {
				return ResourceManager.GetString ("71", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Начинающий.
		/// </summary>
		internal static string _72 {
			get {
				return ResourceManager.GetString ("72", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Разведчик.
		/// </summary>
		internal static string _73 {
			get {
				return ResourceManager.GetString ("73", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Исследователь.
		/// </summary>
		internal static string _74 {
			get {
				return ResourceManager.GetString ("74", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проводник.
		/// </summary>
		internal static string _75 {
			get {
				return ResourceManager.GetString ("75", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to сейчас.
		/// </summary>
		internal static string _76 {
			get {
				return ResourceManager.GetString ("76", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to мин..
		/// </summary>
		internal static string _77 {
			get {
				return ResourceManager.GetString ("77", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to минуты.
		/// </summary>
		internal static string _78 {
			get {
				return ResourceManager.GetString ("78", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to часы.
		/// </summary>
		internal static string _79 {
			get {
				return ResourceManager.GetString ("79", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отправить.
		/// </summary>
		internal static string _8 {
			get {
				return ResourceManager.GetString ("8", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to дни.
		/// </summary>
		internal static string _80 {
			get {
				return ResourceManager.GetString ("80", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to недели.
		/// </summary>
		internal static string _81 {
			get {
				return ResourceManager.GetString ("81", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to месяцы.
		/// </summary>
		internal static string _82 {
			get {
				return ResourceManager.GetString ("82", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поделитесь тем, что происходит рядом с вами....
		/// </summary>
		internal static string _83 {
			get {
				return ResourceManager.GetString ("83", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отметить место.
		/// </summary>
		internal static string _84 {
			get {
				return ResourceManager.GetString ("84", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Текущее место.
		/// </summary>
		internal static string _85 {
			get {
				return ResourceManager.GetString ("85", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Создать новый пост.
		/// </summary>
		internal static string _86 {
			get {
				return ResourceManager.GetString ("86", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пост.
		/// </summary>
		internal static string _87 {
			get {
				return ResourceManager.GetString ("87", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Добавляем.
		/// </summary>
		internal static string _88 {
			get {
				return ResourceManager.GetString ("88", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поделитесь этим с вашими друзьями на Facebook и Twitter.
		/// </summary>
		internal static string _89 {
			get {
				return ResourceManager.GetString ("89", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Уже есть аккаунт?.
		/// </summary>
		internal static string _9 {
			get {
				return ResourceManager.GetString ("9", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spark делает всё, чтобы вы знали последние новинки!.
		/// </summary>
		internal static string _90 {
			get {
				return ResourceManager.GetString ("90", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Включите Push-уведомления, чтобы видеть комментарии других пользователей..
		/// </summary>
		internal static string _91 {
			get {
				return ResourceManager.GetString ("91", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to не сейчас.
		/// </summary>
		internal static string _92 {
			get {
				return ResourceManager.GetString ("92", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Сообщить мне!.
		/// </summary>
		internal static string _93 {
			get {
				return ResourceManager.GetString ("93", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пока ничего интересного здесь!.
		/// </summary>
		internal static string _94 {
			get {
				return ResourceManager.GetString ("94", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Свяжитесь с теми, кто вокруг вас, и получайте уведомления первыми прямо здесь ;).
		/// </summary>
		internal static string _95 {
			get {
				return ResourceManager.GetString ("95", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Уведомления.
		/// </summary>
		internal static string _96 {
			get {
				return ResourceManager.GetString ("96", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Отменить.
		/// </summary>
		internal static string _97 {
			get {
				return ResourceManager.GetString ("97", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ведите меня туда!.
		/// </summary>
		internal static string _98 {
			get {
				return ResourceManager.GetString ("98", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (name) прокомментировал(а) вашу оценку для (location).
		/// </summary>
		internal static string _99 {
			get {
				return ResourceManager.GetString ("99", resourceCulture);
			}
		}
	}
}
