//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public tblAdmin()
        {
            this.tblInvitationCodes = new HashSet<tblInvitationCode>();
        }
    
        public int AdminId { get; set; }
        public int CenterAdminId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<tblInvitationCode> tblInvitationCodes { get; set; }
        public virtual tblWorkCenter tblWorkCenter { get; set; }
    }
}
