//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLabor
    {
        public int LaborId { get; set; }
        public Nullable<int> WorkCenterID { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> BirthPlaceId { get; set; }
        public string FIrstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Age { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> ProfileCompleteness { get; set; }
        public Nullable<bool> IsAgreed { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tblBirthPlace tblBirthPlace { get; set; }
        public virtual tblProfession tblProfession { get; set; }
        public virtual tblWorkCenter tblWorkCenter { get; set; }
    }
}
