//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuperAdmin
    {
        public int SuperAdminId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
    }
}
