//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornalero.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkCenter
    {
        public tblWorkCenter()
        {
            this.tblAdmins = new HashSet<tblAdmin>();
            this.tblLabors = new HashSet<tblLabor>();
            this.tblStops = new HashSet<tblStop>();
        }
    
        public int WorkCenterId { get; set; }
        public int AdminId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Mobile { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public bool IsDisplayEmail { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<tblAdmin> tblAdmins { get; set; }
        public virtual ICollection<tblLabor> tblLabors { get; set; }
        public virtual ICollection<tblStop> tblStops { get; set; }
    }
}
